"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default=False):
    val = os.environ.get(name, '').lower()
    if val == '':
        return default
    return val in ('1', 'true', 'yes', 'on')

def _env_list(name, default):
    val = os.environ.get(name)
    if not val:
        return default
    return [v.strip() for v in val.split(',') if v.strip()]

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须通过环境变量 DJANGO_SECRET_KEY 注入；缺失时回退到开发密钥（仅限本地）。
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-r=9znbk41j@&o2n-$stug1@=g8z8)13u2k$lcr+thrn*b9u0lz',
)

# SECURITY WARNING: don't run with debug turned on in production!
# 本地开发默认 True（run_backend_daemon.py 不设置该变量）；
# 生产环境务必在平台设置 DJANGO_DEBUG=False 显式关闭。
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', ['*'])


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'main',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 生产环境托管 /static（后台/admin + 前端打包资源）
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],  # 生产环境由 Django 托管前端打包产物 index.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 可通过环境变量 DB_PATH 重定向数据库位置（便于挂载数据卷持久化）
        'NAME': os.environ.get('DB_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 生产环境：whitenoise 托管后台/admin 静态资源；同时把前端 build 产物收集进来统一服务
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'frontend' / 'dist']  # 前端 npm run build 输出目录

# Media files（用户上传的图片等）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# SimpleUI 配置
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['关于管理', '作品管理', '主页管理', '认证和授权'],
    'dynamic': True,
    'menus': [
        {
            'name': '关于管理',
            'icon': 'fas fa-user',
            'models': [
                {'name': '个人简介', 'icon': 'fa fa-id-card', 'url': '/admin/main/about/'},
            ]
        },
        {
            'name': '作品管理',
            'icon': 'fas fa-images',
            'models': [
                {'name': '作品分类', 'icon': 'fa fa-folder', 'url': '/admin/main/workcategory/'},
                {'name': '所有作品', 'icon': 'fa fa-photo-video', 'url': '/admin/main/workimage/'},
            ]
        },
        {
            'name': '主页管理',
            'icon': 'fas fa-home',
            'models': [
                {'name': '统一管理（背景/标题/图标）', 'icon': 'fa fa-sliders-h', 'url': '/admin/home-manager/'},
                {'name': '图标数据（精确微调）', 'icon': 'fa fa-icons', 'url': '/admin/main/heroicon/'},
                {'name': '首页配置（数据库）', 'icon': 'fa fa-database', 'url': '/admin/main/heroconfig/'},
            ]
        },
    ],
}
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_LOGO = 'https://simpleui.72wo.com/static/images/logo.png'

# CORS 配置（允许 Vue 前端跨域访问 API）
CORS_ALLOW_ALL_ORIGINS = True
