# Generated by Django 6.0.7 on 2026-07-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='杨帆', max_length=50, verbose_name='姓名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='人物照片')),
                ('role', models.CharField(default='摄影师 / 3D设计师 / AI视觉设计师', max_length=200, verbose_name='身份标签')),
                ('school', models.CharField(default='中央美术学院', max_length=100, verbose_name='毕业院校')),
                ('bio', models.TextField(default='拥有多年视觉设计经验...', verbose_name='个人介绍')),
                ('phone', models.CharField(default='138-0000-0000', max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(default='3421567@qq.com', max_length=254, verbose_name='电子邮箱')),
                ('location', models.CharField(default='中国 · 北京', max_length=100, verbose_name='所在地')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('dribbble', models.URLField(blank=True, verbose_name='Dribbble')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '作品分类',
                'verbose_name_plural': '作品分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='例如: 2025', max_length=10, verbose_name='年份')),
                ('name', models.CharField(max_length=200, verbose_name='奖项名称')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='颁发机构')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.about')),
            ],
            options={
                'verbose_name': '获奖经历',
                'verbose_name_plural': '获奖经历',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='例如: 2025', max_length=50, verbose_name='时间')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_experiences', to='main.about')),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='例如: 2024 - 至今', max_length=50, verbose_name='时间')),
                ('title', models.CharField(max_length=100, verbose_name='职位')),
                ('company', models.CharField(max_length=100, verbose_name='公司')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='main.about')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='作品标题')),
                ('image', models.ImageField(upload_to='works/', verbose_name='作品图片')),
                ('display_mode', models.CharField(choices=[('horizontal', '横屏 16:9'), ('vertical', '竖屏 9:16')], default='horizontal', max_length=20, verbose_name='展示比例')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.workcategory')),
            ],
            options={
                'verbose_name': '作品图片',
                'verbose_name_plural': '作品图片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
