# Generated by Django 6.0.7 on 2026-07-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('camera', '相机'), ('finder', '访达'), ('folder', '文件夹'), ('terminal', '终端')], max_length=20, unique=True, verbose_name='标识')),
                ('label', models.CharField(default='', max_length=20, verbose_name='显示名')),
                ('image', models.ImageField(upload_to='hero_icons/', verbose_name='图标图片')),
                ('pos_x', models.FloatField(default=50, help_text='相对 Hero 舞台左侧的百分比', verbose_name='水平位置(%)')),
                ('pos_y', models.FloatField(default=50, help_text='相对 Hero 舞台顶部的百分比', verbose_name='垂直位置(%)')),
                ('width', models.FloatField(default=160, verbose_name='宽度(px)')),
                ('z_index', models.IntegerField(default=2, help_text='2=在文字后，4=在文字前', verbose_name='层级')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页图标',
                'verbose_name_plural': '首页图标',
                'ordering': ['order'],
            },
        ),
    ]
