# Generated by Django 6.0.7 on 2026-07-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_heroicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(default='Design', max_length=50, verbose_name='标题第一行')),
                ('title_line2', models.CharField(default='Portfolio', max_length=50, verbose_name='标题第二行')),
                ('title_size', models.IntegerField(default=168, help_text='响应式：实际会按屏幕宽度自动缩放', verbose_name='标题最大字号(px)')),
                ('title_font_family', models.CharField(choices=[("'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif", '无衬线（默认）'), ("'Noto Serif SC', 'Songti SC', serif", '衬线 Serif'), ("'SF Mono', 'JetBrains Mono', Consolas, monospace", '等宽 Mono'), ("'Quicksand', 'PingFang SC', sans-serif", '圆润 Quicksand')], default="'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif", max_length=200, verbose_name='标题字体')),
                ('title_gradient', models.CharField(default='linear-gradient(90deg, #ffffff 0%, #e8eef8 20%, #a8c0e0 55%, #5a8ec8 100%)', help_text='CSS linear-gradient 字符串', max_length=300, verbose_name='标题渐变色')),
                ('bg_type', models.CharField(choices=[('none', '无（仅极光）'), ('image', '图片'), ('video', '视频')], default='none', max_length=10, verbose_name='背景类型')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='背景图片')),
                ('bg_video', models.FileField(blank=True, null=True, upload_to='hero/', verbose_name='背景视频')),
                ('bg_video_poster', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='视频封面')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页配置',
                'verbose_name_plural': '首页配置',
            },
        ),
    ]
