# Generated by Django 6.0.7 on 2026-07-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_heroconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroconfig',
            name='title_gradient_dark',
            field=models.CharField(blank=True, default='linear-gradient(90deg, #ffffff 0%, #e8eef8 20%, #a8c0e0 55%, #5a8ec8 100%)', max_length=300, verbose_name='深色页面标题渐变'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='title_gradient_light',
            field=models.CharField(blank=True, default='linear-gradient(90deg, #93c5fd 0%, #60a5fa 30%, #3b82f6 70%, #2563eb 100%)', max_length=300, verbose_name='浅色页面标题渐变'),
        ),
        migrations.AddField(
            model_name='heroicon',
            name='rotation',
            field=models.FloatField(default=0, help_text='顺时针旋转角度，PS 式操作框可调整', verbose_name='旋转角度(deg)'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='bg_type',
            field=models.CharField(choices=[('none', '无'), ('image', '图片'), ('video', '视频')], default='none', max_length=10, verbose_name='背景类型'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='title_gradient',
            field=models.CharField(blank=True, default='linear-gradient(90deg, #ffffff 0%, #e8eef8 20%, #a8c0e0 55%, #5a8ec8 100%)', help_text='历史兼容字段，新逻辑按浅色/深色分别取用下方两个字段', max_length=300, verbose_name='标题渐变色(兼容旧字段)'),
        ),
    ]
