# Generated by Django 6.0.7 on 2026-07-27 03:32
# Edited to use RenameField so existing social-link data is preserved.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_heroconfig_title_gradient_dark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexperience',
            options={'ordering': ['-order'], 'verbose_name': '实习经历', 'verbose_name_plural': '实习经历'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='github',
            new_name='zcool',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='instagram',
            new_name='xiaohongshu',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='dribbble',
            new_name='douyin',
        ),
    ]
