# Generated by Django 6.0.7 on 2026-07-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_projectexperience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexperience',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='公司/组织'),
        ),
        migrations.AlterField(
            model_name='about',
            name='douyin',
            field=models.URLField(blank=True, verbose_name='抖音'),
        ),
        migrations.AlterField(
            model_name='about',
            name='xiaohongshu',
            field=models.URLField(blank=True, verbose_name='小红书'),
        ),
        migrations.AlterField(
            model_name='about',
            name='zcool',
            field=models.URLField(blank=True, verbose_name='站酷'),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='title',
            field=models.CharField(max_length=200, verbose_name='职位'),
        ),
    ]
