# Generated by Django 6.0.7 on 2026-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_company_to_project_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='stat_experience',
            field=models.CharField(default='7+', help_text='例如: 7+', max_length=20, verbose_name='经验年数'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_pages',
            field=models.CharField(default='5000+', help_text='例如: 5000+', max_length=20, verbose_name='项目页面'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_projects',
            field=models.CharField(default='20+', help_text='例如: 20+', max_length=20, verbose_name='落地项目'),
        ),
    ]
